import React, { useEffect, useState } from 'react';
import './App.css';

// Clean single Home component
export default function Home() {
  const [nationalSummary, setNationalSummary] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    (async function load() {
      try {
        const r = await fetch('/output-results/national_evaluation_summary.json');
        const d = await r.json();
        setNationalSummary(d);
      } catch (e) {
        console.error(e);
        setError('Failed to load data');
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  if (loading) return (
    <div className="loading"><div className="spinner"/> <p>Loading KJET Summary...</p></div>
  );

  if (error) return (
    <div className="error"><h2>Error Loading Data</h2><p>{error}</p></div>
  );

  const national = nationalSummary?.national_summary ?? { total_applications: 0, national_eligibility_rate: 0, national_average_score: 0 };
  const topCounties = nationalSummary ? Object.entries(nationalSummary.county_summaries).sort((a,b)=>b[1].total_applications-a[1].total_applications).slice(0,6) : [];

  return (
    <div className="landing app" style={{ fontFamily: "Inter, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif" }}>
      <nav className="navbar"><div className="brand">KJET Analytics</div><div className="nav-links"><a href="/counties">Counties</a></div></nav>
      <header className="landing-header"><h1>KJET National Evaluation</h1><p className="lead">A high-level summary of applications and evaluation outcomes across counties.</p></header>
      <main className="landing-main">
        <section className="national-cards">
          <div className="card"><h4>Total Applications</h4><div className="card-value">{national.total_applications}</div></div>
          <div className="card"><h4>National Eligibility Rate</h4><div className="card-value">{national.national_eligibility_rate}%</div></div>
          <div className="card"><h4>National Average Score</h4><div className="card-value">{(national.national_average_score||0).toFixed(1)}</div></div>
        </section>

        <section className="top-counties">
          <h3>Top Counties by Applications</h3>
          <div className="county-grid">
            {topCounties.map(([name, stats]) => (
              <div key={name} className="county-card">
                <div className="county-name">{name}</div>
                <div className="county-metrics">
                  <div>{stats.total_applications} apps</div>
                  <div>{stats.eligible_applications} eligible</div>
                  <div>Avg: {stats.average_score.toFixed(1)}</div>
                </div>
              </div>
            ))}
          </div>
        </section>
      </main>
      <footer className="landing-footer"><small>Generated by KJET Analytics • {new Date().getFullYear()}</small></footer>
    </div>
  );
}