# Generated by Django 6.0.4 on 2026-08-13 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanResultsCsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.CharField(default='latest', max_length=32)),
                ('file', models.FileField(upload_to='human-csv/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('UPLOAD', 'Uploaded file'), ('SHEET', 'Google Sheet'), ('SEED', 'Seeded from repository')], max_length=16)),
                ('source_url', models.TextField(blank=True)),
                ('sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Validated'), ('PUBLISHED', 'Published'), ('SUPERSEDED', 'Superseded'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=16)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('fingerprint', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'human results CSV',
                'verbose_name_plural': 'human results CSVs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('BUILT', 'Built, awaiting publish'), ('PUBLISHING', 'Publishing'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed'), ('DISCARDED', 'Discarded')], default='PENDING', max_length=16)),
                ('current_step', models.CharField(blank=True, max_length=128)),
                ('steps_done', models.PositiveIntegerField(default=0)),
                ('steps_total', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('diff', models.JSONField(blank=True, default=dict)),
                ('sandbox_path', models.CharField(blank=True, max_length=512)),
                ('published_keys', models.JSONField(blank=True, default=list)),
                ('changed_outputs', models.JSONField(blank=True, default=list)),
                ('celery_task_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('baseline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs_as_baseline', to='pipeline.humanresultscsv')),
                ('csv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='pipeline.humanresultscsv')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
